#!/usr/bin/env Rscript
# Builds inst/tutorials/06-choosing-a-test.ipynb (without outputs).
# Run from the package root:  Rscript scripts/build_nb_06.R
source("scripts/nb_helpers.R")

cells <- list(

series_nav("06"),

md("# Choosing a Test: A Power Study",
   "",
   "**Which heteroscedasticity test should you run? It depends on the pattern.**",
   "",
   "---",
   "",
   "There is no uniformly most powerful heteroscedasticity test. Each one builds an",
   "auxiliary model of the variance, and a test is powerful exactly when that model",
   "matches the *shape* of the true variance. This notebook runs a small Monte-Carlo",
   "study to make the trade-offs concrete and to distil a practical decision guide.",
   "",
   "We compare six tests against four variance shapes, plus a homoscedastic control",
   "to confirm that none of them over-rejects."),

code("library(heteroTests)",
     "ht_set_log_level(\"SILENT\")  # keep simulation loops quiet",
     "library(ggplot2)",
     "theme_set(theme_minimal(base_size = 12))",
     "options(digits = 4)"),

md("## 1. The design",
   "",
   "A single regressor $x \\sim U(1,4)$, mean model $y = 1 + 1.5x + \\varepsilon$, and",
   "five variance regimes for $\\operatorname{sd}(\\varepsilon)$:",
   "",
   "| Regime | $\\operatorname{sd}(\\varepsilon_i)$ | Meaning |",
   "|--------|-----|---------|",
   "| `none` | $1$ | homoscedastic (calibration / size check) |",
   "| `linear` | $0.6 + 0.25\\,x$ | variance grows linearly with $x$ |",
   "| `quadratic` | $0.6 + 0.06\\,x^2$ | variance grows with $x^2$ |",
   "| `step` | $0.7$ or $1.5$ either side of $\\operatorname{median}(x)$ | two-regime variance |",
   "",
   "Effect sizes are deliberately modest ($n = 80$) so that the tests separate",
   "rather than all hitting 100%."),

code("gen <- function(n, pattern) {",
     "  x <- runif(n, 1, 4)",
     "  sd <- switch(pattern,",
     "    none      = rep(1, n),",
     "    linear    = 0.6 + 0.25 * x,",
     "    quadratic = 0.6 + 0.06 * x^2,",
     "    step      = ifelse(x > median(x), 1.5, 0.7))",
     "  data.frame(y = 1 + 1.5 * x + rnorm(n, sd = sd), x = x)",
     "}",
     "",
     "run_test <- function(t, m, d) tryCatch(switch(t,",
     "    White   = performWhiteTest(m, d),   `Breusch-Pagan` = performBPTest(m, d),",
     "    Koenker = performKoenkerTest(m, d), `Goldfeld-Quandt` = performGQTest(m, d, order_by = \"x\"),",
     "    Glejser = performGlejserTest(m, d, \"x\"), Harvey = performHarveyTest(m))$p.value,",
     "  error = function(e) NA_real_)"),

md("## 2. Running the study",
   "",
   "For each (test, regime) cell we record the proportion of 200 replications that",
   "reject at the 5% level. For `none` this is the empirical **size** (should be",
   "$\\approx 5$%); for the others it is **power**."),

code("tests    <- c(\"White\", \"Breusch-Pagan\", \"Koenker\", \"Goldfeld-Quandt\", \"Glejser\", \"Harvey\")",
     "patterns <- c(\"none\", \"linear\", \"quadratic\", \"step\")",
     "set.seed(9); reps <- 200; n <- 80",
     "res <- matrix(0, length(tests), length(patterns), dimnames = list(tests, patterns))",
     "for (p in patterns) for (i in seq_len(reps)) {",
     "  d <- gen(n, p); m <- lm(y ~ x, data = d)",
     "  for (t in tests) {",
     "    pv <- run_test(t, m, d)",
     "    if (!is.na(pv) && pv < 0.05) res[t, p] <- res[t, p] + 1",
     "  }",
     "}",
     "res <- round(100 * res / reps, 1)",
     "res"),

code("long <- data.frame(",
     "  test    = rep(rownames(res), times = ncol(res)),",
     "  pattern = rep(colnames(res), each = nrow(res)),",
     "  value   = as.vector(res))",
     "long$test    <- factor(long$test, levels = rev(rownames(res)))",
     "long$pattern <- factor(long$pattern, levels = colnames(res))",
     "ggplot(long, aes(pattern, test, fill = value)) +",
     "  geom_tile(colour = \"white\") +",
     "  geom_text(aes(label = value), size = 3.5) +",
     "  scale_fill_gradient(low = \"#f7fbff\", high = \"#08519c\", name = \"reject %\") +",
     "  labs(x = \"Variance pattern\", y = NULL,",
     "       title = \"Rejection rate (%) by test and variance pattern\",",
     "       subtitle = \"Column 'none' is the size check (target 5%); others are power\")"),

md("## 3. Reading the results",
   "",
   "**Size (`none` column).** Every test is close to the nominal 5%, with",
   "Goldfeld--Quandt running slightly liberal --- none is broken.",
   "",
   "**Power (other columns).**",
   "",
   "- **Goldfeld--Quandt** is the strongest whenever the ordering variable drives the",
   "  variance (`linear`, `step`): splitting the sample on $x$ aligns perfectly with",
   "  the true pattern.",
   "- **Breusch--Pagan, Koenker and Glejser** form a strong, reliable middle: they",
   "  test the variance directly against $x$ and do well across all shapes.",
   "- **White** is the most general test --- it makes no assumption about the form ---",
   "  but that generality costs degrees of freedom (it includes squares and",
   "  cross-products), so it is *less* powerful against these simple, known shapes.",
   "- **Harvey** trails on additive variance: its log-variance auxiliary regression",
   "  is tuned to multiplicative/exponential heteroscedasticity, which is not what",
   "  these regimes generate.",
   "",
   "The ranking is not a quality ordering --- it is a *matching* problem. The best",
   "test is the one whose auxiliary model resembles the variance you actually have."),

md("## 4. A practical decision guide",
   "",
   "| If you... | Prefer |",
   "|-----------|--------|",
   "| suspect variance tied to one ordered covariate | **Goldfeld--Quandt** (order by it) |",
   "| suspect variance linear in the regressors | **Breusch--Pagan** / **Koenker** |",
   "| are unsure about normality | **Koenker** (studentized) |",
   "| suspect multiplicative / exponential variance | **Harvey** or **Park** (log scale) |",
   "| have no prior idea of the form | **White** (general), then follow up |",
   "| have grouped data | the group-wise tests (notebook 4) |",
   "",
   "And in every case the cheapest insurance is to run two or three complementary",
   "tests, exactly as `runHeteroTests()` does. A disagreement among them is itself",
   "informative --- it points at the *shape* of the problem, as the White-vs-rest",
   "split did in notebook 1.",
   "",
   "---"),

code("sessionInfo()")
)

write_nb(notebook(cells), "inst/tutorials/06-choosing-a-test.ipynb")
