#!/usr/bin/env Rscript
# Builds inst/tutorials/04-group-wise-variance.ipynb (without outputs).
# Run from the package root:  Rscript scripts/build_nb_04.R
source("scripts/nb_helpers.R")

cells <- list(

series_nav("04"),

md("# Group-wise Variance Tests",
   "",
   "**Comparing dispersion across groups --- and the normality trap**",
   "",
   "---",
   "",
   "Not all heteroscedasticity is a smooth function of a continuous regressor.",
   "Often the variance differs across *groups*: treatments in an experiment,",
   "sites in a survey, regimes in a panel. The relevant question becomes",
   "$H_0:\\sigma_1^2 = \\sigma_2^2 = \\cdots = \\sigma_g^2$, and the right tools are the",
   "group-comparison tests.",
   "",
   "`heteroTests` provides the classical and robust members of this family:",
   "**Bartlett**, **Levene**, **Brown--Forsythe** and **Fligner--Killeen**. This",
   "notebook applies them to a textbook data set, validates against `car`, and then",
   "shows --- with a simulation --- why the choice between them matters enormously",
   "when the data are not normal."),

code("library(heteroTests)",
     "ht_set_log_level(\"SILENT\")  # keep simulation loops quiet",
     "library(ggplot2)",
     "theme_set(theme_minimal(base_size = 12))",
     "options(digits = 4)"),

md("## 1. The data",
   "",
   "`InsectSprays` records insect counts under six spray treatments. Count data",
   "typically show variance that grows with the mean, so the groups are a natural",
   "candidate for unequal dispersion."),

code("data(InsectSprays)",
     "InsectSprays$spray <- factor(InsectSprays$spray)",
     "round(tapply(InsectSprays$count, InsectSprays$spray, sd), 2)"),

code("ggplot(InsectSprays, aes(spray, count, fill = spray)) +",
     "  geom_boxplot(show.legend = FALSE, alpha = 0.8) +",
     "  labs(x = \"Spray\", y = \"Insect count\",",
     "       title = \"Dispersion differs markedly across sprays\",",
     "       subtitle = \"Group standard deviations range from ~1.7 to ~6.2\")"),

md("The boxes have visibly different heights: sprays C and E are tight, while A, B",
   "and F are dispersed. The group standard deviations span more than a threefold",
   "range. Now we test it formally."),

md("## 2. The four tests",
   "",
   "Each test reduces to a one-way analysis of dispersion, differing in *what they",
   "analyse*:",
   "",
   "| Test | Operates on | Normality assumption |",
   "|------|-------------|----------------------|",
   "| **Bartlett** | group variances (likelihood ratio) | strong --- assumes normal data |",
   "| **Levene** | $|y_{ij}-\\bar y_j|$ (deviations from the mean) | weak |",
   "| **Brown--Forsythe** | $|y_{ij}-\\tilde y_j|$ (deviations from the median) | weakest (most robust) |",
   "| **Fligner--Killeen** | ranks of absolute deviations | rank-based, very robust |",
   "",
   "All share the package signature `perform*Test(model, data, group)`, where",
   "`model` supplies the residuals and `group` names the factor."),

code("m <- lm(count ~ 1, data = InsectSprays)",
     "summarise <- function(x, label) data.frame(",
     "  Test = label, Statistic = round(unname(x$statistic), 3),",
     "  p.value = signif(x$p.value, 3), Reject_5pct = x$p.value < 0.05)",
     "do.call(rbind, list(",
     "  summarise(performBartlettTest(m, InsectSprays, \"spray\"),       \"Bartlett\"),",
     "  summarise(performLeveneTest(m, InsectSprays, \"spray\"),         \"Levene\"),",
     "  summarise(performBrownForsytheTest(m, InsectSprays, \"spray\"),  \"Brown-Forsythe\"),",
     "  summarise(performFlignerKilleenTest(m, InsectSprays, \"spray\"), \"Fligner-Killeen\")))"),

md("All four agree: the variances are not equal. They will not always agree so",
   "neatly --- which is the point of the next section."),

md("### Validation against `car`",
   "",
   "The Levene implementation should reproduce `car::leveneTest` (mean-centred) to",
   "machine precision."),

code("ours <- performLeveneTest(m, InsectSprays, \"spray\")",
     "ref  <- car::leveneTest(count ~ spray, data = InsectSprays, center = mean)",
     "c(ours = unname(ours$statistic),",
     "  car  = ref[[\"F value\"]][1],",
     "  agree = isTRUE(all.equal(unname(ours$statistic), ref[[\"F value\"]][1])))"),

md("## 3. The normality trap",
   "",
   "Bartlett's test is the most powerful of the four *when the data are normal* ---",
   "but it derives its null distribution from that normality assumption. Under heavy",
   "tails it confuses kurtosis for unequal variance and rejects a true null far too",
   "often. The robust tests (Levene, Brown--Forsythe, Fligner--Killeen) were designed",
   "precisely to avoid this.",
   "",
   "We verify it: simulate groups with **equal variances** but heavy-tailed $t_3$",
   "errors, and measure the rejection rate at the nominal 5% level."),

code("size_study <- function(rng, ng = 4, npg = 25, reps = 200) {",
     "  hit <- c(Bartlett = 0, Levene = 0, `Brown-Forsythe` = 0, `Fligner-Killeen` = 0)",
     "  for (i in seq_len(reps)) {",
     "    g <- factor(rep(seq_len(ng), each = npg))",
     "    d <- data.frame(y = rng(ng * npg), g = g)   # identical dist => equal variance",
     "    m <- lm(y ~ 1, data = d)",
     "    hit[\"Bartlett\"]        <- hit[\"Bartlett\"]        + (performBartlettTest(m, d, \"g\")$p.value < 0.05)",
     "    hit[\"Levene\"]          <- hit[\"Levene\"]          + (performLeveneTest(m, d, \"g\")$p.value < 0.05)",
     "    hit[\"Brown-Forsythe\"]  <- hit[\"Brown-Forsythe\"]  + (performBrownForsytheTest(m, d, \"g\")$p.value < 0.05)",
     "    hit[\"Fligner-Killeen\"] <- hit[\"Fligner-Killeen\"] + (performFlignerKilleenTest(m, d, \"g\")$p.value < 0.05)",
     "  }",
     "  round(100 * hit / reps, 1)",
     "}",
     "set.seed(7)",
     "size_tab <- rbind(",
     "  `Normal errors`        = size_study(function(n) rnorm(n)),",
     "  `Heavy-tailed t(3)`    = size_study(function(n) rt(n, df = 3)))",
     "size_tab"),

code("df_plot <- data.frame(",
     "  test = rep(colnames(size_tab), each = 2),",
     "  errors = rep(rownames(size_tab), times = ncol(size_tab)),",
     "  size = as.vector(t(size_tab)))",
     "ggplot(df_plot, aes(test, size, fill = errors)) +",
     "  geom_col(position = \"dodge\") +",
     "  geom_hline(yintercept = 5, linetype = \"dashed\") +",
     "  labs(x = NULL, y = \"Rejection rate (%) under a true null\",",
     "       fill = NULL, title = \"Empirical size at the nominal 5% level\",",
     "       subtitle = \"Dashed line = nominal 5%. Equal variances in every group.\")"),

md("Under normal errors all four tests sit near 5%. Under $t_3$ errors **Bartlett",
   "rejects roughly half the time** --- a false-positive rate an order of magnitude",
   "too high --- while Levene, Brown--Forsythe and Fligner--Killeen stay close to",
   "nominal. Bartlett is reading heavy tails as unequal variance."),

md("## 4. Which test should you use?",
   "",
   "- **Bartlett** --- most powerful *if you are confident the data are normal*",
   "  (e.g. well-behaved measurement data). Avoid it otherwise.",
   "- **Levene** --- the robust default; mean-centred absolute deviations, good power",
   "  and good calibration. Matches `car::leveneTest`.",
   "- **Brown--Forsythe** --- Levene with median centring; the most robust to skew and",
   "  heavy tails, at a small cost in power.",
   "- **Fligner--Killeen** --- rank-based and highly robust, a strong nonparametric",
   "  choice when the distribution is unknown.",
   "",
   "A practical rule: **default to Levene or Brown--Forsythe**, and reserve Bartlett",
   "for data you have already checked for normality.",
   "",
   "---"),

code("sessionInfo()")
)

write_nb(notebook(cells), "inst/tutorials/04-group-wise-variance.ipynb")
